import React from "react";
import ModuleBrowser, { ModuleCard } from "@/components/ModuleBrowser";
import {
  ShoppingCart,
  FileText,
  Users,
  Globe,
  Package,
  DollarSign,
  ShoppingBag,
  Store,
  Briefcase,
  LayoutGrid,
  Zap,
  Mail,
  Clock,
  Receipt,
  Wrench,
  FolderOpen,
  Calendar as CalendarIcon,
  UserCheck,
  UserPlus,
  Settings,
  Trash2,
  Truck,
  BookOpen,
  PenTool,
  LifeBuoy,
  CreditCard,
  CheckSquare,
  GraduationCap,
  CalendarClock,
  Palmtree,
  MessageSquare,
  PhoneCall,
  MessageCircle,
  BarChart3,
  ClipboardList,
  TrendingUp,
  Send,
  FileSignature,
  HardHat,
  WrenchIcon,
  Smartphone,
  StickyNote,
  Award,
  Phone,
  UtensilsCrossed,
  Plane,
  Waves,
  Ship,
  ShoppingBasket,
  Home,
} from "lucide-react";

const modules: ModuleCard[] = [
  // Sales Category
  {
    icon: ShoppingCart,
    title: "Sales",
    description: "From quotations to invoices",
    path: "/sales",
    category: "Sales",
    color: "bg-gradient-to-br from-green-500 to-emerald-600",
    installed: true,
  },
  {
    icon: FileText,
    title: "Invoicing",
    description: "Invoices & Payments",
    path: "/accounting",
    category: "Accounting",
    color: "bg-gradient-to-br from-blue-500 to-cyan-600",
    installed: true,
  },
  {
    icon: Users,
    title: "CRM",
    description: "Track leads and close opportunities",
    path: "/crm",
    category: "Sales",
    color: "bg-gradient-to-br from-purple-500 to-pink-600",
    installed: true,
  },

  // Website & Marketing
  {
    icon: Globe,
    title: "Website",
    description: "Enterprise website builder",
    path: "/website",
    category: "Website",
    color: "bg-gradient-to-br from-indigo-500 to-purple-600",
  },
  {
    icon: LayoutGrid,
    title: "eCommerce",
    description: "Sell your products online",
    path: "/ecommerce",
    category: "Website",
    color: "bg-gradient-to-br from-orange-500 to-red-600",
    installed: true,
  },
  {
    icon: Mail,
    title: "Email Marketing",
    description: "Design, send and track emails",
    path: "/marketing",
    category: "Marketing",
    color: "bg-gradient-to-br from-pink-500 to-rose-600",
  },
  {
    icon: TrendingUp,
    title: "Social Marketing",
    description: "Manage your social media and website visitors",
    path: "/marketing",
    category: "Marketing",
    color: "bg-gradient-to-br from-blue-400 to-cyan-500",
  },
  {
    icon: Send,
    title: "SMS Marketing",
    description: "Design, send and track SMS",
    path: "/marketing",
    category: "Marketing",
    color: "bg-gradient-to-br from-green-400 to-emerald-500",
  },
  {
    icon: BarChart3,
    title: "Marketing Automation",
    description: "Build automated mailing campaigns",
    path: "/marketing",
    category: "Marketing",
    color: "bg-gradient-to-br from-violet-500 to-purple-600",
  },

  // Inventory & Supply Chain
  {
    icon: Package,
    title: "Inventory",
    description: "Manage your stock and logistics activities",
    path: "/inventory",
    category: "Inventory",
    color: "bg-gradient-to-br from-amber-500 to-orange-600",
    installed: true,
  },
  {
    icon: ShoppingBag,
    title: "Purchase",
    description: "Purchase orders, tenders and agreements",
    path: "/purchases",
    category: "Inventory",
    color: "bg-gradient-to-br from-teal-500 to-cyan-600",
    installed: true,
  },
  {
    icon: Zap,
    title: "Manufacturing",
    description: "Manufacturing Orders & BOMs",
    path: "/manufacturing",
    category: "Manufacturing",
    color: "bg-gradient-to-br from-red-500 to-orange-600",
    installed: true,
  },
  {
    icon: CheckSquare,
    title: "Quality",
    description: "Control the quality of your products",
    path: "/manufacturing",
    category: "Manufacturing",
    color: "bg-gradient-to-br from-green-600 to-teal-600",
  },
  {
    icon: PenTool,
    title: "Product Lifecycle Management (PLM)",
    description: "Manage engineering change orders on products, bills of material",
    path: "/manufacturing",
    category: "Manufacturing",
    color: "bg-gradient-to-br from-slate-500 to-gray-600",
  },

  // Accounting & Finance
  {
    icon: DollarSign,
    title: "Accounting",
    description: "Manage financial and analytic accounting",
    path: "/accounting",
    category: "Accounting",
    color: "bg-gradient-to-br from-emerald-500 to-green-600",
    installed: true,
  },
  {
    icon: Receipt,
    title: "Expenses",
    description: "Submit, validate and reinvoice employee expenses",
    path: "/expenses",
    category: "Accounting",
    color: "bg-gradient-to-br from-yellow-500 to-amber-600",
  },
  {
    icon: BarChart3,
    title: "Consolidation",
    description: "All you need to make financial consolidation",
    path: "/accounting",
    category: "Accounting",
    color: "bg-gradient-to-br from-blue-600 to-indigo-600",
  },

  // Services & Operations
  {
    icon: Store,
    title: "Point of Sale",
    description: "User-friendly PoS interface for shops and restaurants",
    path: "/pos",
    category: "Services",
    color: "bg-gradient-to-br from-teal-500 to-blue-600",
    installed: true,
  },
  {
    icon: Briefcase,
    title: "Project",
    description: "Organize and plan your projects",
    path: "/projects",
    category: "Services",
    color: "bg-gradient-to-br from-indigo-500 to-blue-600",
    installed: true,
  },
  {
    icon: Clock,
    title: "Timesheets",
    description: "Track employee time on tasks",
    path: "/timesheets",
    category: "Services",
    color: "bg-gradient-to-br from-cyan-500 to-blue-600",
  },
  {
    icon: HardHat,
    title: "Field Service",
    description: "Schedule and track onsite operations, time and material",
    path: "/field-service",
    category: "Services",
    color: "bg-gradient-to-br from-orange-600 to-red-600",
  },
  {
    icon: LifeBuoy,
    title: "Helpdesk",
    description: "Track, prioritize, and solve customer tickets",
    path: "/helpdesk",
    category: "Services",
    color: "bg-gradient-to-br from-violet-500 to-purple-600",
    installed: true,
  },
  {
    icon: WrenchIcon,
    title: "Maintenance",
    description: "Track equipment and manage maintenance requests",
    path: "/maintenance",
    category: "Services",
    color: "bg-gradient-to-br from-gray-500 to-slate-600",
  },
  {
    icon: Home,
    title: "Rental",
    description: "Manage rental contracts, deliveries and returns",
    path: "/rental",
    category: "Services",
    color: "bg-gradient-to-br from-rose-500 to-pink-600",
  },
  {
    icon: Wrench,
    title: "Repairs",
    description: "Repair damaged products",
    path: "/repairs",
    category: "Services",
    color: "bg-gradient-to-br from-amber-600 to-orange-600",
  },

  // Human Resources
  {
    icon: UserPlus,
    title: "Employees",
    description: "Centralize employee information",
    path: "/hr",
    category: "Human Resources",
    color: "bg-gradient-to-br from-cyan-500 to-blue-600",
    installed: true,
  },
  {
    icon: UserCheck,
    title: "Recruitment",
    description: "Track your recruitment pipeline",
    path: "/recruitment",
    category: "Human Resources",
    color: "bg-gradient-to-br from-green-500 to-teal-600",
  },
  {
    icon: Palmtree,
    title: "Time Off",
    description: "Allocate PTOs and follow leaves requests",
    path: "/time-off",
    category: "Human Resources",
    color: "bg-gradient-to-br from-blue-400 to-cyan-500",
  },
  {
    icon: ClipboardList,
    title: "Appraisals",
    description: "Assess your employees",
    path: "/appraisals",
    category: "Human Resources",
    color: "bg-gradient-to-br from-purple-500 to-pink-600",
  },
  {
    icon: Award,
    title: "Skills Management",
    description: "Manage skills, knowledge and resume of your employees",
    path: "/skills",
    category: "Human Resources",
    color: "bg-gradient-to-br from-yellow-500 to-amber-600",
  },
  {
    icon: UserPlus,
    title: "Employee Referral",
    description: "Let your employees share job positions and refer their friends",
    path: "/referral",
    category: "Human Resources",
    color: "bg-gradient-to-br from-indigo-500 to-purple-600",
  },
  {
    icon: Clock,
    title: "Attendances",
    description: "Track employee attendance",
    path: "/attendances",
    category: "Human Resources",
    color: "bg-gradient-to-br from-teal-500 to-cyan-600",
  },
  {
    icon: DollarSign,
    title: "Payroll",
    description: "Manage your employee payroll records",
    path: "/payroll",
    category: "Human Resources",
    color: "bg-gradient-to-br from-emerald-500 to-green-600",
    installed: true,
  },
  {
    icon: UtensilsCrossed,
    title: "Lunch",
    description: "Handle lunch orders of your employees",
    path: "/lunch",
    category: "Human Resources",
    color: "bg-gradient-to-br from-orange-500 to-red-600",
  },
  {
    icon: Truck,
    title: "Fleet",
    description: "Manage your fleet and track car costs",
    path: "/fleet",
    category: "Human Resources",
    color: "bg-gradient-to-br from-slate-500 to-gray-600",
  },

  // Productivity
  {
    icon: FolderOpen,
    title: "Documents",
    description: "Document management",
    path: "/documents",
    category: "Productivity",
    color: "bg-gradient-to-br from-blue-500 to-indigo-600",
  },
  {
    icon: FileSignature,
    title: "Sign",
    description: "Send documents to sign online and handle filled copies",
    path: "/sign",
    category: "Productivity",
    color: "bg-gradient-to-br from-violet-500 to-purple-600",
  },
  {
    icon: BookOpen,
    title: "Knowledge",
    description: "Centralize, manage, share and grow your knowledge library",
    path: "/knowledge",
    category: "Productivity",
    color: "bg-gradient-to-br from-cyan-500 to-blue-600",
  },
  {
    icon: MessageSquare,
    title: "Discuss",
    description: "Chat, mail gateway and private channels",
    path: "/discuss",
    category: "Productivity",
    color: "bg-gradient-to-br from-green-500 to-emerald-600",
  },
  {
    icon: CalendarIcon,
    title: "Calendar",
    description: "Schedule employees' meetings",
    path: "/calendar",
    category: "Productivity",
    color: "bg-gradient-to-br from-rose-500 to-pink-600",
  },
  {
    icon: CalendarClock,
    title: "Appointments",
    description: "Allow people to book meetings in your agenda",
    path: "/appointments",
    category: "Productivity",
    color: "bg-gradient-to-br from-purple-500 to-indigo-600",
  },
  {
    icon: Phone,
    title: "VOIP",
    description: "Make calls using a VOIP system",
    path: "/voip",
    category: "Productivity",
    color: "bg-gradient-to-br from-teal-500 to-cyan-600",
  },
  {
    icon: CheckSquare,
    title: "Approvals",
    description: "Create and validate approvals requests",
    path: "/approvals",
    category: "Productivity",
    color: "bg-gradient-to-br from-amber-500 to-orange-600",
  },
  {
    icon: StickyNote,
    title: "Notes",
    description: "Organize your work with memos",
    path: "/notes",
    category: "Productivity",
    color: "bg-gradient-to-br from-yellow-400 to-amber-500",
  },

  // Customizations
  {
    icon: Wrench,
    title: "Studio",
    description: "Create and customize your Odoo apps",
    path: "/admin",
    category: "Customizations",
    color: "bg-gradient-to-br from-gray-600 to-slate-700",
  },
  {
    icon: Smartphone,
    title: "Internet of Things",
    description: "Basic models and helpers to support Internet of Things",
    path: "/iot",
    category: "Customizations",
    color: "bg-gradient-to-br from-blue-600 to-indigo-700",
  },

  // Services - Additional
  {
    icon: CreditCard,
    title: "Subscriptions",
    description: "Generate recurring invoices and manage renewals",
    path: "/subscriptions",
    category: "Services",
    color: "bg-gradient-to-br from-blue-500 to-cyan-600",
  },
  {
    icon: GraduationCap,
    title: "eLearning",
    description: "Manage and publish an eLearning platform",
    path: "/school",
    category: "Services",
    color: "bg-gradient-to-br from-sky-500 to-blue-600",
  },
  {
    icon: CalendarClock,
    title: "Planning",
    description: "Manage your employees' schedule",
    path: "/planning",
    category: "Services",
    color: "bg-gradient-to-br from-indigo-500 to-purple-600",
  },
  {
    icon: CalendarIcon,
    title: "Events",
    description: "Publish events, sell tickets",
    path: "/events",
    category: "Services",
    color: "bg-gradient-to-br from-pink-500 to-rose-600",
  },
  {
    icon: MessageCircle,
    title: "Live Chat",
    description: "Chat with your website visitors",
    path: "/livechat",
    category: "Services",
    color: "bg-gradient-to-br from-green-500 to-teal-600",
  },
  {
    icon: ClipboardList,
    title: "Surveys",
    description: "Send your surveys or share them live",
    path: "/surveys",
    category: "Services",
    color: "bg-gradient-to-br from-violet-500 to-purple-600",
  },

  // Localization & Shipping
  {
    icon: Truck,
    title: "UPS Shipping",
    description: "Send your shippings through UPS and track them online",
    path: "/shipping",
    category: "Localization",
    color: "bg-gradient-to-br from-yellow-700 to-amber-800",
  },
  {
    icon: Plane,
    title: "Fedex Shipping",
    description: "Send your parcels through FedEx",
    path: "/shipping",
    category: "Localization",
    color: "bg-gradient-to-br from-purple-600 to-indigo-700",
  },
  {
    icon: Ship,
    title: "DHL Express Shipping",
    description: "Ship with DHL Express",
    path: "/shipping",
    category: "Localization",
    color: "bg-gradient-to-br from-red-600 to-yellow-500",
  },
  {
    icon: Waves,
    title: "bpost Shipping",
    description: "Belgian postal service integration",
    path: "/shipping",
    category: "Localization",
    color: "bg-gradient-to-br from-blue-600 to-yellow-500",
  },
  {
    icon: ShoppingBasket,
    title: "Amazon Connector",
    description: "Import Amazon orders and sync deliveries",
    path: "/integrations",
    category: "Localization",
    color: "bg-gradient-to-br from-orange-500 to-amber-600",
  },

  // Specialty
  {
    icon: UtensilsCrossed,
    title: "Restaurant",
    description: "Manage your restaurant operations",
    path: "/restaurant",
    category: "Services",
    color: "bg-gradient-to-br from-rose-500 to-red-600",
    installed: true,
  },
  {
    icon: GraduationCap,
    title: "School",
    description: "Complete school management system",
    path: "/school",
    category: "Services",
    color: "bg-gradient-to-br from-sky-500 to-blue-600",
  },
  {
    icon: Home,
    title: "Real Estate",
    description: "Manage properties and real estate operations",
    path: "/real-estate",
    category: "Services",
    color: "bg-gradient-to-br from-slate-500 to-gray-600",
  },
  {
    icon: PhoneCall,
    title: "Medical",
    description: "Healthcare and medical practice management",
    path: "/medical",
    category: "Services",
    color: "bg-gradient-to-br from-fuchsia-500 to-pink-600",
  },
  {
    icon: Users,
    title: "Contacts",
    description: "Centralize your address book",
    path: "/contacts",
    category: "Productivity",
    color: "bg-gradient-to-br from-blue-500 to-cyan-600",
  },
  {
    icon: Trash2,
    title: "Data Recycle",
    description: "Find old records and archive/delete them",
    path: "/admin",
    category: "Customizations",
    color: "bg-gradient-to-br from-gray-500 to-slate-600",
  },
];

export default function Apps() {
  // Get category from URL if present
  const urlParams = new URLSearchParams(window.location.search);
  const categoryFromUrl = urlParams.get('category');

  return (
    <ModuleBrowser
      modules={modules}
      title="Apps"
      description="Discover and manage your business applications"
      initialCategory={categoryFromUrl || "All"}
    />
  );
}
